hide_topics:
  hide_topics_enabled:
    default: true
    client: true
  hide_topics_categories:
    default: ""
    type: list
    client: true
  hide_topics_name:
    default: "Hide Topics Plugin"
    client: true
    type: text
